### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by lukas-gitl** [refnode/liquid#1]
Any chance development on this is going to be picket up again?

**Comment by refnode** [comment]
Hi, not dead because I'm interested in that project anymore, but I don't have a chance to continue before end of april.

**Comment by lukas-gitl** [comment]
Thanks for the reply!

For anyone else looking at rendering liquid templates in python. We are using a js template engine for now like so:

``` python
import execjs


def render(template, defaults):
    with open("liquid.js", "r") as f:
        ctx = execjs.compile(
            "var document = {'getElementsByTagName': function() {return 0}};" +
            f.read() +
            "function render__(src, vars) {" +
            "var tmpl = Liquid.parse( src );" +
            "return tmpl.render(vars);" +
            "}"
        )
    return ctx().call("render__", template, defaults)
```

Where the liquid js file is 
https://github.com/mattmccray/liquid.js/blob/cb1dab774cbf92c5936ecde0417bcdd53ffd0316/dist/liquid.js

**Comment by refnode** [comment]
Project is obsolete for me.
Archiving.
